let currentUser=JSON.parse(localStorage.getItem("msUser"))||null;
let posts=JSON.parse(localStorage.getItem("msPosts"))||[
{id:1,name:"Arun Potter",username:"arunpotter",text:"Welcome to M S BLOGGING! ⚡ May your ideas always find their magic.",image:"",likes:15,liked:false,comments:[{name:"Priya Granger",text:"This is magical! ✨"},{name:"Rahul Weasley",text:"Amazing post!"}],reposts:2},
{id:2,name:"Priya Granger",username:"priyagranger",text:"Learning JavaScript today! Knowledge is the most powerful magic. 📚✨",image:"",likes:24,liked:false,comments:[{name:"Arun Potter",text:"Great thought! 🪄"},{name:"Aisha Luna",text:"Love this!"}],reposts:4},
{id:3,name:"Rahul Weasley",username:"rahulweasley",text:"Building something magical with AI and code! 🪄💻",image:"",likes:8,liked:false,comments:[{name:"Priya Granger",text:"Awesome work!"}],reposts:1}];
let following=JSON.parse(localStorage.getItem("msFollowing"))||[];
let notifications=JSON.parse(localStorage.getItem("msNotifications"))||[];
const users=[{name:"Arun Potter",username:"arunpotter"},{name:"Priya Granger",username:"priyagranger"},{name:"Rahul Weasley",username:"rahulweasley"},{name:"Aisha Luna",username:"aishaluna"}];

function googleLogin(){currentUser={name:"Google Wizard",username:"googlewizard",email:"google@example.com"};localStorage.setItem("msUser",JSON.stringify(currentUser));startApp()}
function normalLogin(){let name=document.getElementById("loginName").value.trim(),email=document.getElementById("loginEmail").value.trim();if(!name||!email){alert("Please enter your Wizard Name and Email.");return}currentUser={name,username:name.toLowerCase().replace(/\s+/g,""),email};localStorage.setItem("msUser",JSON.stringify(currentUser));startApp()}
function startApp(){if(!currentUser){document.getElementById("loginPage").classList.remove("hidden");document.getElementById("app").classList.add("hidden");return}document.getElementById("loginPage").classList.add("hidden");document.getElementById("app").classList.remove("hidden");updateUserUI();displayPosts();displaySuggestions();displayNotifications();updateProfile()}
function updateUserUI(){let l=currentUser.name.charAt(0).toUpperCase();document.getElementById("miniAvatar").innerText=l;document.getElementById("miniName").innerText=currentUser.name;document.getElementById("miniUsername").innerText="@"+currentUser.username;document.getElementById("profileName").innerText=currentUser.name;document.getElementById("profileUsername").innerText="@"+currentUser.username}
function createPost(){let text=document.getElementById("postText").value.trim(),image=document.getElementById("imageUrl").value.trim();if(!text){alert("Write a magical thought first! 🪄");return}posts.unshift({id:Date.now(),name:currentUser.name,username:currentUser.username,text,image,likes:0,liked:false,comments:[],reposts:0});savePosts();document.getElementById("postText").value="";document.getElementById("imageUrl").value="";updateCounter();displayPosts();updateProfile();addNotification("Your magical post was published.")}
function displayPosts(list=posts){let feed=document.getElementById("feed");feed.innerHTML="";if(!list.length){feed.innerHTML='<div class="card"><p>No magical posts found.</p></div>';return}list.forEach(p=>feed.innerHTML+=createPostHTML(p))}
function createPostHTML(p){let l=p.name.charAt(0).toUpperCase();return `<article class="card"><div class="post-header"><div class="avatar small-avatar">${l}</div><div><b>${escapeHTML(p.name)}</b><div class="handle">@${escapeHTML(p.username)} · just now</div></div></div><div class="post-text">${escapeHTML(p.text)}</div>${p.image?`<img src="${escapeAttribute(p.image)}" class="post-image" onerror="this.style.display='none'">`:""}<div class="actions"><span class="comment-hidden"></span><button onclick="repost(${p.id})">🔁 ${p.reposts}</button><button onclick="likePost(${p.id})">${p.liked?"❤️":"🤍"} ${p.likes}</button><button onclick="sharePost()">🔗 Share</button></div></article>`}
function likePost(id){let p=posts.find(x=>x.id===id);if(!p)return;if(p.liked){p.likes--;p.liked=false}else{p.likes++;p.liked=true;addNotification("You cast a Like spell! ❤️")}savePosts();displayPosts()}
function repost(id){let p=posts.find(x=>x.id===id);if(!p)return;p.reposts++;posts.unshift({...p,id:Date.now(),text:"🔁 Reposted: "+p.text,likes:0,liked:false});savePosts();displayPosts();addNotification("You shared a magical post.")}
function sharePost(){if(navigator.share){navigator.share({title:"M S BLOGGING",text:"Check out this magical post!",url:location.href})}else{navigator.clipboard.writeText(location.href);alert("Magical link copied! 🪄")}}
function searchPosts(){let q=document.getElementById("search").value.toLowerCase();displayPosts(posts.filter(p=>p.text.toLowerCase().includes(q)||p.name.toLowerCase().includes(q)||p.username.toLowerCase().includes(q)))}
function followUser(username,button){if(following.includes(username)){following=following.filter(x=>x!==username);button.innerText="Follow"}else{following.push(username);button.innerText="Following";addNotification("You are now following @"+username)}localStorage.setItem("msFollowing",JSON.stringify(following));displaySuggestions();updateProfile()}
function displaySuggestions(){let a=document.getElementById("suggestions"),b=document.getElementById("peopleList");a.innerHTML="";b.innerHTML="";users.forEach(u=>{let f=following.includes(u.username);let h=`<div class="person"><div><b>${u.name}</b><div class="handle">@${u.username}</div></div><button class="follow" onclick="followUser('${u.username}',this)">${f?"Following":"Follow"}</button></div>`;a.innerHTML+=h;b.innerHTML+=h})}
function addNotification(text){notifications.unshift({text,time:new Date().toLocaleTimeString()});notifications=notifications.slice(0,20);localStorage.setItem("msNotifications",JSON.stringify(notifications));displayNotifications()}
function displayNotifications(){let c=document.getElementById("notificationList");c.innerHTML="";if(!notifications.length){c.innerHTML='<div class="card"><p>No owl post yet. 🦉</p></div>';return}notifications.forEach(n=>c.innerHTML+=`<div class="notification card">🦉 <div><b>M S BLOGGING</b><p>${escapeHTML(n.text)}</p><small>${n.time}</small></div></div>`);document.getElementById("notificationCount").innerText=notifications.length}
function showSection(s){document.querySelectorAll(".section").forEach(x=>x.classList.add("hidden"));document.getElementById(s).classList.remove("hidden");if(s==="profile")updateProfile()}
function updateProfile(){let mine=posts.filter(p=>p.username===currentUser.username);document.getElementById("postCount").innerText=mine.length;
document.getElementById("followingCount").innerText=following.length;
document.getElementById("followersCount").innerText=128;let c=document.getElementById("profilePosts");c.innerHTML="";mine.forEach(p=>c.innerHTML+=createPostHTML(p))}
function editProfile(){let n=prompt("Enter your new wizard name:",currentUser.name);if(!n)return;currentUser.name=n.trim();currentUser.username=n.toLowerCase().replace(/\s+/g,"");localStorage.setItem("msUser",JSON.stringify(currentUser));updateUserUI();updateProfile()}
function updateCounter(){let t=document.getElementById("postText").value;document.getElementById("counter").innerText=t.length+" / 280"}
function toggleTheme(){document.body.classList.toggle("light-magic")}
function clearPosts(){if(!confirm("Clear all your magical posts?"))return;posts=posts.filter(p=>p.username!==currentUser.username);savePosts();displayPosts();updateProfile()}
function savePosts(){localStorage.setItem("msPosts",JSON.stringify(posts))}
function logout(){localStorage.removeItem("msUser");currentUser=null;location.reload()}
function escapeHTML(t){return t.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;")}
function escapeAttribute(t){return t.replace(/"/g,"&quot;").replace(/'/g,"&#039;")}
startApp();
